### ISSUE TITLE
How did you use the function snr_based_clustering?

### ISSUE THREAD

**Issue by zhanglijun95** [gohyojun15/ANT_diffusion#2]
Hi, I would like to know how you use the function snr_based_clustering? What will be the input snr for it? Will be the snr computed on the noisy latent or the noise itself? Thanks for reply in advance!

**Comment by gohyojun15** [comment]
Hello!

To cluster timesteps $t$ into $N$ groups, you can use the function snr_based_clustering. In this context, $SNR$ means the signal-to-noise ratio across timestep $t$! Therefore, the input of that function can be a Numpy array having signal-to-noise ratios for all of the timesteps.

If you have further questions, feel free to ask!

**Comment by gohyojun15** [comment]
Sorry for late response!

I think the latter one is correct!
For clarification, please see [Variational Diffusion Models](https://arxiv.org/abs/2107.00630). In that work, SNR at timesteps (noise levels) are well defined.

**Comment by zhanglijun95** [comment]
Thank you! That's clear.
